name: Daily AI Podcast

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar c贸digo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Instalar Bibliotecas (Modo For莽ado)
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai feedparser duckdb edge-tts nest_asyncio pyTelegramBotAPI pydub requests

    - name: Rodar o Rob么
      env:
        CHAVE_GEMINI: ${{ secrets.CHAVE_GEMINI }}
        TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
        # Se voc锚 j谩 colocou o ID fixo no main.py, essa linha abaixo n茫o 茅 essencial, mas mal n茫o faz
        CHAT_ID_TELEGRAM: ${{ secrets.CHAT_ID_TELEGRAM }}
      run: python main.py

    - name: Salvar Mem贸ria
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: " Atualizando mem贸ria"
        file_pattern: "*.duckdb"
